#!/bin/bash
# SSH Bot Rain Map - Easy Deploy Script
# This script helps users deploy the SSH Bot Rain Map on their VPS

set -e

echo "🔥 SSH Bot Rain Map - Easy Deploy 🔥"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Docker is installed
check_docker() {
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first:"
        echo "  Ubuntu/Debian: sudo apt update && sudo apt install docker.io docker-compose"
        echo "  CentOS/RHEL: sudo yum install docker docker-compose"
        echo "  Or visit: https://docs.docker.com/get-docker/"
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi

    print_success "Docker and Docker Compose are installed"
}

# Detect SSH log path
detect_ssh_log() {
    print_status "Detecting SSH log file location..."

    SSH_LOG_PATH=""

    # Common SSH log locations
    if [ -f "/var/log/auth.log" ]; then
        SSH_LOG_PATH="/var/log/auth.log"
        print_success "Found SSH log at: $SSH_LOG_PATH (Ubuntu/Debian)"
    elif [ -f "/var/log/secure" ]; then
        SSH_LOG_PATH="/var/log/secure"
        print_success "Found SSH log at: $SSH_LOG_PATH (RHEL/CentOS)"
    elif [ -f "/var/log/messages" ]; then
        SSH_LOG_PATH="/var/log/messages"
        print_success "Found SSH log at: $SSH_LOG_PATH (Some systems)"
    else
        print_warning "Could not auto-detect SSH log file"
        echo "Common locations:"
        echo "  - /var/log/auth.log (Ubuntu, Debian)"
        echo "  - /var/log/secure (RHEL, CentOS, Fedora)"
        echo "  - /var/log/messages (Some systems)"
        read -p "Enter the path to your SSH log file: " SSH_LOG_PATH
    fi
}

# Get server location
get_server_location() {
    print_status "Getting your server location..."

    # Try to get location from ip-api.com
    LOCATION_DATA=$(curl -s "http://ip-api.com/json/" 2>/dev/null || echo "")

    if [ -n "$LOCATION_DATA" ]; then
        LAT=$(echo "$LOCATION_DATA" | grep -o '"lat":[^,]*' | cut -d':' -f2 | tr -d '"')
        LON=$(echo "$LOCATION_DATA" | grep -o '"lon":[^,]*' | cut -d':' -f2 | tr -d '"')
        CITY=$(echo "$LOCATION_DATA" | grep -o '"city":"[^"]*"' | cut -d':' -f2 | tr -d '"')
        COUNTRY=$(echo "$LOCATION_DATA" | grep -o '"country":"[^"]*"' | cut -d':' -f2 | tr -d '"')

        if [ -n "$LAT" ] && [ -n "$LON" ]; then
            VPS_LAT="$LAT"
            VPS_LON="$LON"
            VPS_LABEL="${CITY:-My VPS}, ${COUNTRY:-Unknown}"
            print_success "Detected location: $VPS_LABEL ($VPS_LAT, $VPS_LON)"
            return
        fi
    fi

    print_warning "Could not auto-detect server location"
    echo "Please enter your server coordinates:"
    read -p "Latitude (e.g., 40.4168 for Madrid): " VPS_LAT
    read -p "Longitude (e.g., -3.7038 for Madrid): " VPS_LON
    read -p "Server label (e.g., 'My VPS in Madrid'): " VPS_LABEL
}

# Create .env file
create_env_file() {
    print_status "Creating configuration file..."

    cat > .env << EOF
# SSH Bot Rain Map Configuration
# Generated by deploy.sh on $(date)

# SSH log file path
SSH_LOG_PATH=$SSH_LOG_PATH

# Your server location
VPS_LAT=$VPS_LAT
VPS_LON=$VPS_LON
VPS_LABEL=$VPS_LABEL

# Geolocation provider (ip-api is free, no key needed)
GEO_PROVIDER=ip-api
IPINFO_TOKEN=

# Frontend port (change if 3000 is in use)
FRONTEND_PORT=3000

# Backend settings
MAX_EVENTS=10000
GEO_CACHE_TTL=86400
WS_BROADCAST_INTERVAL=1.0
EOF

    print_success "Configuration saved to .env"
}

# Deploy the application
deploy_app() {
    print_status "Building and starting SSH Bot Rain Map..."

    # Use docker compose (newer versions) or docker-compose (older versions)
    if docker compose version &> /dev/null; then
        COMPOSE_CMD="docker compose"
    else
        COMPOSE_CMD="docker-compose"
    fi

    $COMPOSE_CMD up -d --build

    print_success "SSH Bot Rain Map is now running!"
    echo ""
    echo "🌐 Access your dashboard at: http://$(hostname -I | awk '{print $1}'):3000"
    echo "   (or http://localhost:3000 if accessing locally)"
    echo ""
    echo "🔍 Check logs with: $COMPOSE_CMD logs -f"
    echo "🛑 Stop with: $COMPOSE_CMD down"
    echo ""
    print_warning "Note: It may take a few minutes for attacks to appear on the map"
    print_warning "The tool only visualizes existing SSH login attempts"
}

# Main execution
main() {
    check_docker
    detect_ssh_log
    get_server_location
    create_env_file
    deploy_app

    echo ""
    print_success "🎉 Deployment completed successfully!"
    echo ""
    echo "Your SSH Bot Rain Map is now monitoring your server for bot attacks."
    echo "Watch the 'rain' of login attempts from around the world!"
    echo ""
    echo "💡 Pro tip: Share your dashboard URL with friends to show them"
    echo "   the constant background noise of automated SSH scanning."
}

# Run main function
main "$@"